---
artifactId: checkmk-java-client
groupId: com.oneandone
artifactVersion: 1.1
artifactDescription: REST API client library for Checkmk
hideGenerationTimestamp: true
developerEmail: stephan.fuhrmann@ionos.com
developerOrganization: IONOS SE
developerOrganizationUrl: https://www.ionos.com/
developerName: Stephan Fuhrmann
additionalProperties:
  invokerPackage: com.ionos.network.checkmk.openapi
  apiPackage: com.ionos.network.checkmk.openapi.api
  modelPackage: com.ionos.network.checkmk.openapi.model
  dateLibrary: java8
  java8: true
  scmUrl: https://github.com/1and1/checkmk-java-client
  scmConnection: scm:git:ssh://git@github.com:1and1/checkmk-java-client.git
  scmDeveloperConnection: scm:git:ssh://git@github.com:1and1/checkmk-java-client.git
  performBeanValidation: true
  useBeanValidation: true
