#! /bin/bash
set -e
export OUR_VERSION=1.1
export GENERATOR_VERSION=5.4.0
export OPENAPI_VERSION=2.2.0p12
CLEANED_OPENAPI_VERSION=$(echo $OPENAPI_VERSION | tr "p" "." )
export ARTIFACT_VERSION=${OUR_VERSION}.${CLEANED_OPENAPI_VERSION}
