# Extracts the OpenAPI specs from multiple Checkmk versions and stores them as an artifact

name: Extract all OpenAPI specs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  extract-all-openapi:
    uses: 1and1/checkmk-java-client/.github/workflows/extract-openapi.yaml@main
    with:
      cmk_version: ${{ matrix.version }}
      target_artifact: openapi
      file_name: checkmk_${{ matrix.version }}_openapi.yml
    strategy:
      matrix:
        version:
        - 2.1.0p36
        - 2.2.0p12
        - 2.2.0p14 
