# Extracts the OpenAPI specs from multiple Checkmk versions and stores them as an artifact

name: Extract all OpenAPI specs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  extract-all-openapi:
    uses: 1and1/checkmk-java-client/.github/workflows/extract-openapi.yaml@main
    with:
      cmk_version: ${{ matrix.version }}
      target_artifact: openapi
      file_name: checkmk_${{ matrix.version }}_openapi.yml
    strategy:
      matrix:
        version:
          - 2.0.0p1
          - 2.0.0p2
          - 2.0.0p3
          - 2.0.0p4
          - 2.0.0p5
          - 2.0.0p6
          - 2.0.0p7
          - 2.0.0p8
          - 2.0.0p9
          - 2.0.0p10
          - 2.0.0p11
          - 2.0.0p12
          - 2.0.0p13
          - 2.0.0p14
          - 2.0.0p15
          - 2.0.0p16
          - 2.0.0p17
          - 2.0.0p18
          - 2.0.0p19
          - 2.0.0p20
          - 2.0.0p21
          - 2.0.0p22
          - 2.0.0p23
          - 2.0.0p24
          - 2.0.0p25
          - 2.0.0p26
          - 2.0.0p27
          - 2.0.0p28
          - 2.0.0p29
          - 2.0.0p30
          - 2.0.0p31
          - 2.0.0p32
          - 2.0.0p33
          - 2.0.0p34
          - 2.0.0p35
          - 2.0.0p36
          - 2.0.0p37
          - 2.0.0p38
          - 2.0.0p39
          - 2.1.0p1
          - 2.1.0p2
          - 2.1.0p3
          - 2.1.0p4
          - 2.1.0p5
          - 2.1.0p6
          - 2.1.0p8
          - 2.1.0p9
          - 2.1.0p10
          - 2.1.0p11
          - 2.1.0p12
          - 2.1.0p13
          - 2.1.0p14
          - 2.1.0p15
          - 2.1.0p16
          - 2.1.0p17
          - 2.1.0p18
          - 2.1.0p19
          - 2.1.0p20
          - 2.1.0p21
          - 2.1.0p22
          - 2.1.0p23
          - 2.1.0p24
          - 2.1.0p25
          - 2.1.0p26
          - 2.1.0p27
          - 2.1.0p28
          - 2.1.0p29
          - 2.1.0p30
          - 2.1.0p31
          - 2.1.0p32
          - 2.1.0p33
          - 2.1.0p34
          - 2.1.0p35
          - 2.1.0p36
          - 2.2.0p1
          - 2.2.0p2
          - 2.2.0p3
          - 2.2.0p4
          - 2.2.0p5
          - 2.2.0p6
          - 2.2.0p7
          - 2.2.0p8
          - 2.2.0p9
          - 2.2.0p11
          - 2.2.0p12
          - 2.2.0p14
